language: node_js
node_js:
  - node
cache: npm
install:
  - npm install -g redoc-cli
script:
  - redoc-cli bundle openapi.yaml
before_deploy:
  - touch .nojekyll
  - mv redoc-static.html index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false
