version: '3'

services:
  api:
    image: blbridges96/project-api
    environment:
      - DEBUG
    ports:
      - '5000:5000'
    deploy:
      replicas: 1
    networks:
      project-net:
        # This allows "api" to work in swarm mode.
        aliases:
          - api

  worker:
    image: blbridges96/project-worker
    env:
      API_HOST=api
      API_PORT=5000
      API_DB=0
    deploy:
      replicas: 5
    networks:
      project-net:

  redis:
    image: redis:5.0.0-alpine
    # Port does not need to be exposed to the host.
    deploy:
      replicas: 1
    networks:
      project-net:

networks:
  project-net:
